### ISSUE TITLE
Error when send sms

### ISSUE THREAD

**Issue by absemetov** [uapixart/laravel-turbosms#1]
(1/1) ErrorException
Argument 2 passed to Uapixart\LaravelTurbosms\Turbosms::send() must be an instance of Uapixart\LaravelTurbosms\string, string given, called in /var/www/rzkAnw/rzk.com.ua/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 221 and defined

**Comment by mkuzmych** [comment]
fixed, plese check

**Comment by absemetov** [comment]
How to fix this?
I change:
//public function send($phones, string $text)
public function send($phones, $text)

**Comment by mkuzmych** [comment]
I make make new release, update
